site_name: Stavrophora Docs
site_url: https://utsmok.github.io/stavrophora/
repo_url: https://github.com/utsmok/stavrophora/
site_author: S. Mok

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
watch:
  - src/stavrophora
